### PR TITLE
Merge and update to the A320 Family

### PR DESCRIPTION
**Pull request by ghost**
Merge and update to the A320 Family

### CODE REVIEW

**Comment by FGDATA** [comment]
Hi David
This is now pulled into FGMEMBERS
Great Job
IH-COL

**Comment by ghost** [comment]
Sure is. Thanks .  Is it possible to add me to the FGMEMBERS ? I have a lot
more liveries to make,for the 737,757..various Airbus planes,so it it would
be easier to add them directly that way.

Regards

2015-07-06 20:45 GMT+02:00 FGDATA notifications@github.com:

**Comment by FGDATA** [comment]
Hi David
Your invitation has been sent
IH-COL

**Comment by ghost** [comment]
Got it and done.

Thank you man.

Regards

2015-07-07 18:11 GMT+02:00 FGDATA notifications@github.com:

**Comment by IAHM-COL** [comment]
yes. It seems you are now learning the git ways :D
IH=COL

**Comment by ghost** [comment]
I have tried out the BAe 146 and it wasn't showing up in the A/C list.

Found the error,fixed it but I'm not sure weather I should send it to the
repo.... I don't want to be responsible if that plane is not working on 3.5
or the future 3.6  ....

What do you think?

2015-07-09 17:41 GMT+02:00 Israel Hernandez notifications@github.com:

**Comment by FGDATA** [comment]
Do you know how to make a branch? 
It is definitely possibly not recommended to push that directly into master. But if you have a suggestion you want to share, it is better to create a topic branch. Push it to the repo. Then create a merge request from that branch to master, and leave a comment, plus tag important authors about it (ie, @JWocky and @IH-COL would apply)

I will send you more specific instructions in a minute or two

**Comment by JWocky** [comment]
Author already here ... A/C list? As in not in the launcher? What was your fix?

**Comment by ghost** [comment]
That could work because that same thing is probably preventing Jwocky's 767
form showing up in FG 3.4  so bring it on :))

2015-07-09 18:00 GMT+02:00 FGDATA notifications@github.com:

**Comment by ghost** [comment]
See this line  :

<PropertyList include="Aircraft/JPack/Interface.xml">

That's the line in the set.xml which is preventing it from showing up.

Bt changing it to just <PropertyList>   it works.

2015-07-09 18:01 GMT+02:00 JWocky notifications@github.com:

**Comment by FGDATA** [comment]
:(
No it does not

That will allow it to be seen by the launcher, but it will be a broken plane

**Comment by ghost** [comment]
It's not a broken plane. The BAe was working.... and I will try out the 767
the same way.

2015-07-09 18:05 GMT+02:00 FGDATA notifications@github.com:

**Comment by IAHM-COL** [comment]
Well... believe it or not, that change brakes the plane, regardless of the launcher seen it now.
Its a bit complicated, but it can be summarized as follow:
1. The aircrafts that say that JPack interface.xml in the include need the JPack additional Package installed
   https://github.com/FGMEMBERS/JPack

The JPack includes most of its functionality. That is the airplane is not coded in the aircraft directory, but outside, in the JPack Package _or library_.

Removing that line on the PropertyList set file chops off all the functionality imported.
So you get in the best case a bare bones aircraft. Not a functioning one.

Ive sent you an email with a long discussion on the forum about this. The current conclusion is that the bug resides in the launcher, and it needs to be fixed by the core developers (since the launcher is part of the core parts of the FGFS)

I hope it clarifies.
IH_COL

**Comment by JWocky** [comment]
Well, it may works with the Bae-146 for the moment because I called the autopilot directly and have all the initialization of properties in the -set.xml. But it works only as long as I use parts of the JPack for the cockpit. So, the only reason, it doesn't break the BAe is, that I haven't connected any systems yet. The JPack is there for a reason ...

**Comment by ghost** [comment]
ok... well i do hope these planes will work...

regards

2015-07-09 18:15 GMT+02:00 JWocky notifications@github.com:

**Pull request merged**
